// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzZ2WqEbg4xTXMkQEFWWKCbu7jXD_ZVwk',
    appId: '1:864462847563:web:bead60aff07bf95540d7ce',
    messagingSenderId: '864462847563',
    projectId: 'againbloc',
    authDomain: 'againbloc.firebaseapp.com',
    storageBucket: 'againbloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnd3IXnhX-zLVBdU2DDBkiBdjRIGalloc',
    appId: '1:864462847563:android:9de1a1b4b046abe740d7ce',
    messagingSenderId: '864462847563',
    projectId: 'againbloc',
    storageBucket: 'againbloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqxr2dJ5u5dRBl2iyjlUsNaQDmbqdwCDE',
    appId: '1:864462847563:ios:3542a95e8655a6c040d7ce',
    messagingSenderId: '864462847563',
    projectId: 'againbloc',
    storageBucket: 'againbloc.appspot.com',
    iosBundleId: 'com.example.againbloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqxr2dJ5u5dRBl2iyjlUsNaQDmbqdwCDE',
    appId: '1:864462847563:ios:3542a95e8655a6c040d7ce',
    messagingSenderId: '864462847563',
    projectId: 'againbloc',
    storageBucket: 'againbloc.appspot.com',
    iosBundleId: 'com.example.againbloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzZ2WqEbg4xTXMkQEFWWKCbu7jXD_ZVwk',
    appId: '1:864462847563:web:2a7a5a2938a6e31840d7ce',
    messagingSenderId: '864462847563',
    projectId: 'againbloc',
    authDomain: 'againbloc.firebaseapp.com',
    storageBucket: 'againbloc.appspot.com',
  );

}